version: "3.8"

services:
	db:
		image: postgres:16
		container_name: dashline-postgres
		restart: unless-stopped
		environment:
			POSTGRES_USER: postgres
			POSTGRES_PASSWORD: postgres
			POSTGRES_DB: dashline
		ports:
			- "5432:5432"
		volumes:
			- db_data:/var/lib/postgresql/data
		healthcheck:
			test: ["CMD-SHELL", "pg_isready -U postgres"]
			interval: 10s
			timeout: 5s
			retries: 5

volumes:
	db_data:
		driver: local

